name: Go Lint

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: lint
        uses: dominikh/staticcheck-action@v1  # Running Staticcheck(https://github.com/dominikh/staticcheck-action)
        with:
          version: "latest"