name: Go Build

on: [push]
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: lint
        # Running Staticcheck
        # https://staticcheck.dev/docs/running-staticcheck/ci/github-actions/
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
      - name: test
        run: go test -v ./...
