name: Go Build

on: [push]
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  setup-go:
    uses: ./.github/workflows/setup-go.yaml
    with:
      go-version: '1.24'

  lint:
    needs: setup-go
    runs-on: ubuntu-latest
    steps:
    # Running Staticcheck
    # https://staticcheck.dev/docs/running-staticcheck/ci/github-actions/
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"

  test:
    needs: setup-go
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: go test -v ./...
